from ._pyo3_object_store import ObjectStore

def copy(store: ObjectStore, from_: str, to: str) -> None: ...
async def copy_async(store: ObjectStore, from_: str, to: str) -> None: ...
def copy_if_not_exists(store: ObjectStore, from_: str, to: str) -> None: ...
async def copy_if_not_exists_async(store: ObjectStore, from_: str, to: str) -> None: ...
