from ._list import ObjectMeta
from ._pyo3_object_store import ObjectStore

def head(store: ObjectStore, location: str) -> ObjectMeta: ...
async def head_async(store: ObjectStore, location: str) -> ObjectMeta: ...
