from ._pyo3_object_store import ObjectStore

def rename(store: ObjectStore, from_: str, to: str) -> None: ...
async def rename_async(store: ObjectStore, from_: str, to: str) -> None: ...
def rename_if_not_exists(store: ObjectStore, from_: str, to: str) -> None: ...
async def rename_if_not_exists_async(
    store: ObjectStore, from_: str, to: str
) -> None: ...
